### ISSUE TITLE
TRAILS: error StatusError: Forbidden

### ISSUE THREAD

**Issue by dani4ko03** [drventure/MMM-Dorba-Trails#1]
TRAILS: error StatusError: Forbidden is the message displayed both on the module and in the error log. The module worked correctly once after it stayed on for a long while. Upon seeing that it was properly displaying the default trails I  edited the  trailIDs so it would display the trails that I ride regularly and restarted the MagicMirror and got the same StatusError: Forbidden message. Have not be able to figure out what might be causing this error message, I even tried to  switch networks and connect to a different network because I know that the Forbidden error usually means network issues. Again no luck. I'm all out of ideas as to what might be causing this.

**Comment by drventure** [comment]
Hi

Yes, I've been trying to work with the guys at dorba for a while now, but not having much luck. Basically what's happening is that they've balcklisted the app from querying their site.

I'm guessing it's because maybe it hits it too much (although as I recall, I only query the site twice a day).

But that's just a guess. I've never gotten any concrete response from them as to why I might be blacklisted or how I might be able to pull the query data "more politely" I suppose....?

Anyway, unfortunately, at this point, i'm pretty much out of ideas as well. I used to use that Applet on my own magic mirror, and it's still there, still showing the unavailable most to the time as well.

I say "most" because +very+ occasionally, it'll suddenly work and pull down status on the set of trails I have set. But, usually, within a day, its back to "Unavailable"

You wouldn't happen to know anyone at Dorba that could help would you?

**Comment by dani4ko03** [comment]
I do not know anyone at dorba, but I am willing to try and help with this. I can try and contact trailforks and dorba and ask about this and see if maybe they'll give me an answer. I was also wondering if they have banned the MagicMirror app from making requests could we have another server get the data and have the MagicMirror request the status of the trails form there instead of directly from their site?

**Comment by drventure** [comment]
Yes, that could work, but, I'd kinda like to "play nice" if you know what I mean rather than just brute force it. If my little app really is posing an issue for their site, I was hoping I could get someone to let me know why so I could correct the problem.

What few MM's there are in the Dallas ft area (I can't imagine anyone living anywhere else would be interested in Dorba trails) surely can't swamp the site, esp if it's only hitting it a few times a day.

But they may be blacklisting for some other reason... I just don't know.

**Comment by drventure** [comment]
What's really odd is they actually have a public facing API for getting trail data. You'd think with that, it'd be ok to access it from something like an MM

**Comment by dani4ko03** [comment]
Wouldnt your module work with any trails on the TrailForks website, but even then I am not sure that there would be that many people using it because it is called Dorba trails.

**Comment by dani4ko03** [comment]
You could also make a request to use the API, or have you already tried that? Maybe that way they will turn a little more attention to this project.

**Comment by drventure** [comment]
Yeah, that's what I'd asked about before but never got a response.

**Comment by dani4ko03** [comment]
Since you are already in contact with DORBA about this I will not be bothering them for now. I can imagine that there is much they can do anyway. I already messaged TrailForks so we'll see if they respond. Hopefully, they won't ignore me and message me back so we can figure this out because this module was the reason I started on this mirror and now I'm determined to make it work.

**Comment by dani4ko03** [comment]
I see that on the TrailForks website, there is a function that shows you if your message has been read or not. DId they ever open your message/s?

**Comment by drventure** [comment]
I think when I originally reached out, it was to the Dorba guys. I've gone directly to trailforks and sent a query that way. We'll see if they get back to me.

**Comment by dani4ko03** [comment]
Good news!
![Screenshot_20230929-223035_Chrome](https://github.com/drventure/MMM-Dorba-Trails/assets/132539573/7d619f39-2120-427c-a3a4-03f80ad12628)

**Comment by dani4ko03** [comment]
Let me know what to message him in response.

**Comment by drventure** [comment]
I got in touch with Mark Tay at Trailforks. Waiting to hear back.

Right now, I'm not specifying any particular user-agent, the plugin just
uses the Open source BENT Javascript library to make a pretty vanilla HTTP
request against the site.

Here's the default configuration
        url: "
https://www.trailforks.com/widgets/region_list/?rids={trailIDs}&cols=title,status,city_title,last_report_ts
",
        trailIDs: "3723,19031,5025",

The list of trailids comes from their site, and is just substituted in  for
{trailids}

But it'd be a pretty simple change to add headers or make whatever change
would be required, I believe.

In fact, you can type that exact query into a browser and get back the
status for the listed trail ids.

I suppose I could specify a user-agent the same as what Firefox or Edge
specifies.

I just want to be sure I'm playing by their rules if there are any
specifically for this sort of thing

Darin

**Comment by canadaka** [comment]
You could also just add some unique param to the URL that I can filter on.

**Comment by KristjanESPERANTO** [comment]
@drventure and @canadaka: What do you think about a parameter `client=MMM-Dorba-Trails` like that: <https://www.trailforks.com/widgets/region_list/?rids=3721&cols=title,status,city_title,last_report_ts&client=MMM-Dorba-Trails>?

I prepared this in my PR: https://github.com/drventure/MMM-Dorba-Trails/pull/2/commits/f0aaa5e805889e67ba9aba86f497fa67b24c3af2

**Comment by KristjanESPERANTO** [comment]
Glad you've already accepted the PR, @drventure! 🙂 

Has @canadaka already set up the filter? I can't test it yet.

**Comment by drventure** [comment]
It might be this weekend before I can get a chance to test it myself.
I haven't heard anything from @canadaka yet, but adding a client parm like that seems like a super simple way to ID the requester.

**Comment by canadaka** [comment]
I added a whitelist for requests with that client string to that URL.

**Comment by drventure** [comment]
Perfect, I'll try it as soon as I can free up some time.

Thanks for taking a look at this!

**Comment by KristjanESPERANTO** [comment]
> I added a whitelist for requests with that client string to that URL.

Nice! It's working on my setup :smiley:  Thanks! 🎉
